-- MySQL Script generated by MySQL Workbench
-- Mon May 30 08:48:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema brief
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema brief
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `brief` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `brief` ;

-- -----------------------------------------------------
-- Table `brief`.`categories_des_films`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brief`.`categories_des_films` (
  `idcategories_des_films` INT NOT NULL,
  `action` VARCHAR(45) NOT NULL,
  `comedie` VARCHAR(45) NOT NULL,
  `aventure` VARCHAR(45) NOT NULL,
  `drame` VARCHAR(45) NOT NULL,
  `horreur` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategories_des_films`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `brief`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brief`.`clients` (
  `idclients` INT NOT NULL AUTO_INCREMENT,
  `NOM` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idclients`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `brief`.`films`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brief`.`films` (
  `idfilms` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NOT NULL,
  `date_de_sortie` DATETIME NOT NULL,
  `durée` DATETIME NOT NULL,
  `realisateur` VARCHAR(45) NOT NULL,
  `categories_des_films_idcategories_des_films` INT NOT NULL,
  PRIMARY KEY (`idfilms`),
  INDEX `fk_films_categories_des_films1_idx` (`categories_des_films_idcategories_des_films` ASC) VISIBLE,
  CONSTRAINT `fk_films_categories_des_films1`
    FOREIGN KEY (`categories_des_films_idcategories_des_films`)
    REFERENCES `brief`.`categories_des_films` (`idcategories_des_films`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `brief`.`creation_modification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brief`.`creation_modification` (
  `idcreation_modification` INT NOT NULL AUTO_INCREMENT,
  `date_de_creation` DATETIME NOT NULL,
  `date_de_modification` VARCHAR(45) NOT NULL,
  `films_idfilms` INT NOT NULL,
  PRIMARY KEY (`idcreation_modification`),
  INDEX `fk_creation_modification_films1_idx` (`films_idfilms` ASC) VISIBLE,
  CONSTRAINT `fk_creation_modification_films1`
    FOREIGN KEY (`films_idfilms`)
    REFERENCES `brief`.`films` (`idfilms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `brief`.`films_loues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brief`.`films_loues` (
  `idfilms_loues` INT NOT NULL AUTO_INCREMENT,
  `date_de_location` DATETIME NOT NULL,
  `date_de_retour` DATETIME NOT NULL,
  `categories_des_films_idcategories_des_films` INT NOT NULL,
  PRIMARY KEY (`idfilms_loues`),
  INDEX `fk_films_loues_categories_des_films1_idx` (`categories_des_films_idcategories_des_films` ASC) VISIBLE,
  CONSTRAINT `fk_films_loues_categories_des_films1`
    FOREIGN KEY (`categories_des_films_idcategories_des_films`)
    REFERENCES `brief`.`categories_des_films` (`idcategories_des_films`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `brief`.`payements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brief`.`payements` (
  `idpayements` INT NOT NULL AUTO_INCREMENT,
  `date_de_payement` DATETIME NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `montant` VARCHAR(45) NOT NULL,
  `clients_idclients` INT NOT NULL,
  PRIMARY KEY (`idpayements`),
  INDEX `fk_payements_clients1_idx` (`clients_idclients` ASC) VISIBLE,
  CONSTRAINT `fk_payements_clients1`
    FOREIGN KEY (`clients_idclients`)
    REFERENCES `brief`.`clients` (`idclients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `brief`.`clients_has_films`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brief`.`clients_has_films` (
  `clients_idclients` INT NOT NULL,
  `films_loues_idfilms_loues` INT NOT NULL,
  INDEX `fk_clients_has_films_clients1_idx` (`clients_idclients` ASC) VISIBLE,
  INDEX `fk_clients_has_films_films_loues1_idx` (`films_loues_idfilms_loues` ASC) VISIBLE,
  CONSTRAINT `fk_clients_has_films_clients1`
    FOREIGN KEY (`clients_idclients`)
    REFERENCES `brief`.`clients` (`idclients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clients_has_films_films_loues1`
    FOREIGN KEY (`films_loues_idfilms_loues`)
    REFERENCES `brief`.`films_loues` (`idfilms_loues`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
